//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sTranslate.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Translation
    {
        public int Id { get; set; }
        public string FromText { get; set; }
        public string ToText { get; set; }
        public string Context { get; set; }
        public string Property { get; set; }
        public string Criteria { get; set; }
        public string FromLang { get; set; }
        public string ToLang { get; set; }
        public System.DateTime Inserted { get; set; }
        public string InsertedBy { get; set; }
        public Nullable<System.DateTime> Updated { get; set; }
        public string UpdatedBy { get; set; }
    }
}
